'use client';

import MemesTitle from '@/app/sections/memes/components/title';
import Carousel from '@/app/sections/memes/components/carousel';
import MemesTabs from '@/app/sections/memes/components/tabs';

const MemesView = (props: any) => {
  const {} = props;

  return (
    <div className="">
      <MemesTitle />
      <Carousel data={list} />
      <MemesTabs />
    </div>
  );
};

export default MemesView;

// FIXME mock data
const list = [
  {
    "created_at": 1737738742000,
    "updated_at": 1738743974000,
    "id": 986989,
    "account": "8mLxzbaiprhz4zXNEWxqeGr93XUF1MnCKVw4iVGbSgSh",
    "account_data": {
      "id": 9,
      "created_at": "2025-01-04T16:02:48Z",
      "updated_at": "2025-02-17T01:00:00Z",
      "address": "8mLxzbaiprhz4zXNEWxqeGr93XUF1MnCKVw4iVGbSgSh",
      "level": 1,
      "vip_type": "normal",
      "vip_expiration_time": 0,
      "vip_start_time": 0,
      "icon": "",
      "banner": "",
      "name": "",
      "followers": 2,
      "following": 2,
      "like_num": 100,
      "using_like_num": 0,
      "un_like_num": 0,
      "super_like_num": 0,
      "using_super_like_num": 0,
      "buy_super_like_num": 0,
      "using_buy_super_like_num": 0,
      "boost_num": 10,
      "using_boost_num": 0,
      "buy_boost_num": 0,
      "using_buy_boost_num": 0,
      "collect_num": 0,
      "project_num": 15,
      "pump_project_num": 0,
      "proxy_fee": "0",
      "referral_fee": "0",
      "time": 1736006528,
      "is_follower": false,
      "education": "",
      "buy_amount": "0"
    },
    "address": "PLYqZC9RgTnaU8BGZ9J4ES7NE3R3NEHCMxPaN47KhE2",
    "DApp": "sexy",
    "pool_address": "3HeGYJY8HZkY9Y68dffT6dAEZJK28h5J5ZEJbNGgrT82",
    "token_name": "Bearsnoear",
    "token_symbol": "BEARSNOEAR",
    "token_decimals": 6,
    "token_supply": "0",
    "initial_sol": "0",
    "icon": "https://flipn.s3.us-east-1.amazonaws.com/flipn/stg/24Vht4UPCCB.jpg",
    "video": "https://flipn.s3.us-east-1.amazonaws.com/flipn/stg/24Vht4UPCCB.jpg",
    "ticker": "B",
    "about_us": "Bears no ears is B!",
    "website": "",
    "x": "",
    "tg": "",
    "discord": "",
    "like": 7,
    "un_like": 0,
    "super_like": 0,
    "pre_paid": 0,
    "pre_paid_amount": "0",
    "collect": 0,
    "comment": 0,
    "is_collect": false,
    "is_like": false,
    "is_un_like": false,
    "is_pre_paid": false,
    "boost_time": 0,
    "status": 0,
    "is_show": false,
    "concentrated_holdings": false,
    "initiative_launching": false,
    "is_king": false,
    "last_king_time": 0,
    "share_num": 0,
    "total_amount": 0,
    "bonding_progress": 11.98,
    "king_progress": 0,
    "time": 1737738734000
  },
  {
    "created_at": 1738466753000,
    "updated_at": 1739521093000,
    "id": 988340,
    "account": "EF6PjPYp2f8rjRzvyQ6EMcmbbTneAGc8rvBqAvonquKU",
    "account_data": {
      "id": 146,
      "created_at": "2025-01-06T03:41:51Z",
      "updated_at": "2025-02-17T01:00:00Z",
      "address": "EF6PjPYp2f8rjRzvyQ6EMcmbbTneAGc8rvBqAvonquKU",
      "level": 1,
      "vip_type": "normal",
      "vip_expiration_time": 0,
      "vip_start_time": 0,
      "icon": "https://flipn.s3.us-east-1.amazonaws.com/flipn/stg/DRhaIfire.png",
      "banner": "/img/upload-banner.png",
      "name": "",
      "followers": 2,
      "following": 2,
      "like_num": 100,
      "using_like_num": 0,
      "un_like_num": 1,
      "super_like_num": 0,
      "using_super_like_num": 0,
      "buy_super_like_num": 0,
      "using_buy_super_like_num": 0,
      "boost_num": 0,
      "using_boost_num": 0,
      "buy_boost_num": 0,
      "using_buy_boost_num": 0,
      "collect_num": 0,
      "project_num": 15,
      "pump_project_num": 0,
      "proxy_fee": "0",
      "referral_fee": "0",
      "time": 1736134871,
      "is_follower": false,
      "education": "",
      "buy_amount": "0"
    },
    "address": "7FzvQJNYczfasHMSrGUA8y3WZS2m9Kt8WM9n8wExo824",
    "DApp": "sexy",
    "pool_address": "2P2xDDFSR22mxQYqwczHZMPdgXXqp6og7T44pJRSTq5H",
    "token_name": "rainbow01",
    "token_symbol": "RAINBOW01",
    "token_decimals": 6,
    "token_supply": "0",
    "initial_sol": "0",
    "icon": "https://flipn.s3.us-east-1.amazonaws.com/flipn/stg/zwZrfnbow01.png",
    "video": "https://flipn.s3.us-east-1.amazonaws.com/flipn/stg/XCmoq0xBI2x.mp4",
    "ticker": "RR",
    "about_us": "With years of experience, we provide top-tier technical support and deliver highquality results across various industries.",
    "website": "",
    "x": "",
    "tg": "",
    "discord": "",
    "like": 7,
    "un_like": 0,
    "super_like": 0,
    "pre_paid": 0,
    "pre_paid_amount": "0",
    "collect": 0,
    "comment": 0,
    "is_collect": false,
    "is_like": false,
    "is_un_like": false,
    "is_pre_paid": false,
    "boost_time": 0,
    "status": 0,
    "is_show": false,
    "concentrated_holdings": false,
    "initiative_launching": false,
    "is_king": false,
    "last_king_time": 0,
    "share_num": 0,
    "total_amount": 0,
    "bonding_progress": 11.98,
    "king_progress": 0,
    "time": 1738466745000
  },
  {
    "created_at": 1738466897000,
    "updated_at": 1738917527000,
    "id": 988341,
    "account": "2MhmmzSapVNo3vpogKFYt7Ec8es9CQp7HDGzYwxRCFtZ",
    "account_data": {
      "id": 310,
      "created_at": "2025-01-07T08:52:22Z",
      "updated_at": "2025-02-17T01:00:00Z",
      "address": "2MhmmzSapVNo3vpogKFYt7Ec8es9CQp7HDGzYwxRCFtZ",
      "level": 1,
      "vip_type": "normal",
      "vip_expiration_time": 0,
      "vip_start_time": 0,
      "icon": "https://flipn.s3.us-east-1.amazonaws.com/flipn/stg/eic6fMG3159.jpg",
      "banner": "/img/upload-banner.png",
      "name": "RCFtZ",
      "followers": 1,
      "following": 0,
      "like_num": 100,
      "using_like_num": 0,
      "un_like_num": 0,
      "super_like_num": 0,
      "using_super_like_num": 0,
      "buy_super_like_num": 0,
      "using_buy_super_like_num": 0,
      "boost_num": 0,
      "using_boost_num": 0,
      "buy_boost_num": 0,
      "using_buy_boost_num": 0,
      "collect_num": 0,
      "project_num": 7,
      "pump_project_num": 0,
      "proxy_fee": "0",
      "referral_fee": "0",
      "time": 1736239902,
      "is_follower": false,
      "education": "PhD",
      "buy_amount": "0"
    },
    "address": "VrXbBHb1c6UQWbjcWwsnULV5gSH9RpnHNB9a8cQEKi8",
    "DApp": "sexy",
    "pool_address": "Gm26TS6PHbpta7rBw7Qar6kQhqUAe6238fnrzYYWoGzJ",
    "token_name": "Coyotee",
    "token_symbol": "COYOTEE",
    "token_decimals": 6,
    "token_supply": "0",
    "initial_sol": "0",
    "icon": "https://flipn.s3.us-east-1.amazonaws.com/flipn/stg/GTNgwcep.jpg",
    "video": "https://flipn.s3.us-east-1.amazonaws.com/flipn/stg/1i8Mfep9JPt.mp4",
    "ticker": "Coyote",
    "about_us": "A coyote is a wild canine native to North America that is known for its adaptability and opportunistic feeding habits.",
    "website": "",
    "x": "",
    "tg": "",
    "discord": "",
    "like": 5,
    "un_like": 0,
    "super_like": 0,
    "pre_paid": 2,
    "pre_paid_amount": "2010152.2842639593908629",
    "collect": 0,
    "comment": 0,
    "is_collect": false,
    "is_like": false,
    "is_un_like": false,
    "is_pre_paid": false,
    "boost_time": 0,
    "status": 0,
    "is_show": false,
    "concentrated_holdings": false,
    "initiative_launching": false,
    "is_king": false,
    "last_king_time": 0,
    "share_num": 0,
    "total_amount": 0,
    "bonding_progress": 11.98,
    "king_progress": 0,
    "time": 1738466888000
  },
];
